--- 
dota2: 
  enabled: true
  cron: "*/15 * * * * *"
  dotabuff: www.dotabuff.com
  steam: www.steam.com
  team: 
    - 
      nickName: test1
      slackId: 1
      steamId: 1
    - 
      nickName: test2
      slackId: 1
      steamId: 1
btc-watcher: 
  enabled: true
  cron: "*/10 * * * * *"
  rate: XBTZAR
  channels: 
    - http://www.slack1.com
    - http://www.slack2.com
foo: 
  enabled: false
  cron: "*/10 * * * * *"
  url: www.foo.com
  team: 
    - 
      nickName: bar1
      bnetId: 1
      eloId: 1
    - 
      nickName: baz2
      bnetId: 2
      eloId: 2