--- 
dota2: 
  cron: "*/10 * * * * *"
  dotabuff: www.dotabuff.com
  steam: www.steam.com
  team: 
    - 
      nickName: test1
      slackId: 1
      steamId: 1
    - 
      nickName: test2
      slackId: 1
      steamId: 1
foo: 
  cron: "*/10 * * * * *"
  url: www.foo.com
  team: 
    - 
      nickName: bar1
      bnetId: 1
      eloId: 1
    - 
      nickName: baz2
      bnetId: 2
      eloId: 2