--- 
dota2: 
  enabled: false
  cron: "*/15 * * * * *"
  dotabuff: www.dotabuff.com
  steam: www.steam.com
  team: 
    - 
      nickName: test1
      slackId: 1
      steamId: 1
    - 
      nickName: test2
      slackId: 1
      steamId: 1
btc-watcher: 
  enabled: true
  cron: "*/60 * * * * *"
  rate: 
    - XBTZAR
  channels: 
    - http://www.slack1.com
    - http://www.slack2.com
